inherit_from: .rubocop_todo.yml

require: rubocop-rails
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Layout/LineLength:
  Enabled: true
  AutoCorrect: true
  Max: 120
Style/Documentation:
  Enabled: false