openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'https://tawa-me-api.herokuapp.com'
  - url: 'http://localhost:5000'
    description: ''
paths:
  /api/twitter/jobs:
    post:
      summary: execute job
      operationId: post-api-twitter-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      description: ''
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                screen_name:
                  type: string
                  example: tawachandesu
                layer_count:
                  type: integer
                  example: '1'
                with_user_detail:
                  type: boolean
                  example: false
        description: ''
    parameters: []
    get:
      summary: fetch jobs data
      operationId: get-api-twitter-jobs
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties: {}
      parameters: []
      tags:
        - tweet
  /api/twitter/jobs/reset:
    get:
      summary: ''
      operationId: get-api-twitter-jobs-reset
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
      tags:
        - tweet
  /api/tweets:
    get:
      summary: Your GET endpoint
      tags:
        - tweet
      responses: {}
      operationId: get-api-tweets
    post:
      summary: ''
      operationId: post-api-tweets
      responses:
        '200':
          description: OK
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TweetData'
        description: ''
      tags:
        - tweet
components:
  schemas:
    TweetData:
      title: TweetData
      type: object
      properties:
        tweet_id:
          type: number
        text:
          type: string
        is_reply:
          type: boolean
        user_id:
          type: number
        user_name:
          type: string
        user_screen_name:
          type: string
        user_friends_count:
          type: number
        user_followers_count:
          type: number
        lang:
          type: string
        quote_count:
          type: number
        reply_count:
          type: number
        retweet_count:
          type: number
        favorite_count:
          type: number
        hashtags:
          type: string
        tweeted_at:
          type: string
        is_quote:
          type: boolean
        is_retweet:
          type: boolean
        original_tweet_id:
          type: number
      required:
        - tweet_id
        - text
        - is_reply
        - user_id
        - user_name
        - user_screen_name
        - user_friends_count
        - user_followers_count
        - lang
        - quote_count
        - reply_count
        - retweet_count
        - favorite_count
        - hashtags
        - tweeted_at
        - is_quote
        - is_retweet
  securitySchemes: {}
