openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/twitter/users:
    get:
      summary: Twitterのユーザーデータ
      tags: []
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  screen_name:
                    type: string
                  unique_id:
                    type: string
                  created_at:
                    type: string
                  updated_at:
                    type: string
      operationId: get-api-twitter-users
components:
  schemas: {}
