openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
paths:
  /api/twitter/users:
    get:
      summary: Twitterのユーザーデータ
      tags: []
      responses: {}
      operationId: get-api-twitter-users
components:
  schemas: {}
