openapi: 3.0.0
info:
  title: api
  version: '1.0'
servers:
  - url: 'https://tawa-me-api.herokuapp.com'
  - url: 'http://localhost:3000'
    description: ''
paths:
  /api/twitter/users/execute:
    post:
      summary: execute job fetching user data from Twitter
      operationId: post-api-twitter-users
      responses:
        '200':
          description: OK
      description: twitterからユーザー情報取得ジョブを実行
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                screen_name:
                  type: string
                  example: tawachandesu
        description: ''
  /api/twitter/users:
    get:
      summary: fetch users
      operationId: get-api-twitter-users
      responses:
        '200':
          description: OK
      description: ユーザー一覧を取得
components:
  schemas: {}
